/**
 * Voorbeelddata voor ThreatPulse. Vervang dit door je eigen feed.
 * Velden komen overeen met de `Vuln` typedef in ThreatPulse.jsx.
 * (CVE-id's hieronder zijn fictief / voor demo-doeleinden.)
 */
export const sampleVulns = [
  {
    rank: 1,
    cveId: 'CVE-2026-1234',
    name: 'CoffeeLeak',
    buzz: 87,
    trend: 'rising',
    news: 12,
    social: 2400,
    researchers: 8,
    source: 24,
    severity: 'CRITICAL',
    flags: ['KEV', 'PoC'],
    summary: 'Een fout in de sessie-afhandeling van de populaire reverse-proxy CoffeeProxy laat een aanvaller zonder in te loggen het geheugen uitlezen — inclusief tokens en wachtwoorden.',
    riskFor: 'publieke webservers met CoffeeProxy 3.x zonder de patch van gisteren.',
    spark: [18, 26, 24, 39, 55, 72, 87],
  },
  {
    rank: 2,
    cveId: 'CVE-2026-0991',
    name: 'Naamloos',
    buzz: 71,
    trend: 'rising',
    news: 7,
    social: 1600,
    researchers: 6,
    source: 15,
    severity: 'HIGH',
    flags: ['PoC'],
    summary: 'Een lek in de PDF-render-engine van diverse mailclients voert code uit zodra een bijlage wordt voorvertoond — geen klik nodig.',
    riskFor: 'desktop-mailclients die bijlagen automatisch previewen.',
    spark: [30, 34, 33, 47, 52, 65, 71],
  },
  {
    rank: 3,
    cveId: 'CVE-2026-2087',
    name: 'GhostMTA',
    buzz: 64,
    trend: 'stable',
    news: 9,
    social: 900,
    researchers: 5,
    source: 18,
    severity: 'CRITICAL',
    flags: ['KEV'],
    summary: 'Een verkeerd geconfigureerde standaardregel in een veelgebruikte mailserver laat onbekenden mail versturen namens jouw domein.',
    riskFor: 'beheerders van zelf-gehoste mailservers met de standaardconfig.',
    spark: [60, 57, 63, 59, 64, 61, 64],
  },
  {
    rank: 4,
    cveId: 'CVE-2026-1450',
    name: 'Naamloos',
    buzz: 52,
    trend: 'cooling',
    news: 5,
    social: 1100,
    researchers: 3,
    source: 11,
    severity: 'MEDIUM',
    flags: ['PoC'],
    summary: 'Een lek in een wijdverspreide datum-bibliotheek laat een aanvaller via geprepareerde invoer de server laten vastlopen.',
    riskFor: 'Node-backends die invoer direct doorgeven aan de bibliotheek.',
    spark: [80, 74, 69, 63, 58, 55, 52],
  },
  {
    rank: 5,
    cveId: 'CVE-2025-9982',
    name: 'LoopHole',
    buzz: 41,
    trend: 'cooling',
    news: 4,
    social: 600,
    researchers: 4,
    source: 9,
    severity: 'HIGH',
    flags: ['KEV', 'PoC'],
    summary: 'Een omzeiling van de tweestapsverificatie in een bekende VPN-appliance, al sinds vorige maand bekend maar nog volop besproken.',
    riskFor: 'organisaties met de VPN-appliance op de rand van hun netwerk.',
    spark: [66, 60, 57, 52, 48, 44, 41],
  },
];

export default sampleVulns;
